name: in_app_purchases_interface
description: Interface Package for interpackage communications for in app purchases and shared classes with the Plugins made by www.linkfive.io
version: 1.0.0
homepage: https://linkfive.io
repository: https://github.com/LinkFive/flutter-in_app_purchases_paywall

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
